name=input("enter the student name :")
age=input("enter the student age :")
address=input("enter the student address:")
print("\n -- student details -- ")
print("name:",name)
print("age:",age)
print("address:",address)

name=input("enter teacher name:")
subject=input("enter the subject:")
courcecode=input("enter the corcecode")

print("\n---teacher details---")
print("name:",name)
print("subject:",subject)
print("corcecode:",courcecode)
